name: InfiniteHomes
version: 1.0
main: com.user404_.infinitehomes.InfiniteHomes
api-version: 1.21
commands:
  sethome:
    description: Set a home with the given name.
    usage: /sethome <name>
  delhome:
    description: Delete a home with the given name.
    usage: /delhome <name>
  home:
    description: Teleport to a home with the given name.
    usage: /home <name>
  homecount:
    description: Set the global home limit (OP only).
    usage: /homecount <number>