name: InfiniteHomes
version: 1.1
main: com.user404_.infinitehomes.InfiniteHomes
website: https://www.spigotmc.org/resources/infinitehomes-unlimited-or-configurable-homes-system.128492/
api-version: 1.21
commands:
  sethome:
    description: Set a home with the given name.
    usage: /sethome <name>
  delhome:
    description: Delete a home with the given name.
    usage: /delhome <name>
  home:
    description: Teleport to a home with the given name.
    usage: /home <name>
  homes:
    description: List all your homes.
    usage: /homes
  homecount:
    description: Set the global home limit (OP only).
    usage: /homecount <number>